// <auto-generated />
using AspNetCoreContentLocalization.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreContentLocalization.Migrations
{
    [DbContext(typeof(Storage))]
    partial class StorageModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCoreContentLocalization.Data.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("DescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("NameId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .IsUnique();

                    b.HasIndex("DescriptionId")
                        .IsUnique();

                    b.HasIndex("NameId")
                        .IsUnique();

                    b.ToTable("Books");
                });

            modelBuilder.Entity("AspNetCoreContentLocalization.Data.Entities.Culture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Cultures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "tr",
                            Name = "Türkçe"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = 3,
                            Code = "de",
                            Name = "Deutsch"
                        });
                });

            modelBuilder.Entity("AspNetCoreContentLocalization.Data.Entities.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("NameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NameId");

                    b.ToTable("Librarys");
                });

            modelBuilder.Entity("AspNetCoreContentLocalization.Data.Entities.Localization", b =>
                {
                    b.Property<int>("LocalizationSetId")
                        .HasColumnType("int");

                    b.Property<int>("CultureId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocalizationSetId", "CultureId");

                    b.HasIndex("CultureId");

                    b.ToTable("Localizations");
                });

            modelBuilder.Entity("AspNetCoreContentLocalization.Data.Entities.LocalizationSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("LocalizationSets");
                });

            modelBuilder.Entity("AspNetCoreContentLocalization.Data.Entities.Book", b =>
                {
                    b.HasOne("AspNetCoreContentLocalization.Data.Entities.LocalizationSet", "Author")
                        .WithOne()
                        .HasForeignKey("AspNetCoreContentLocalization.Data.Entities.Book", "AuthorId")
                        .IsRequired();

                    b.HasOne("AspNetCoreContentLocalization.Data.Entities.LocalizationSet", "Description")
                        .WithOne()
                        .HasForeignKey("AspNetCoreContentLocalization.Data.Entities.Book", "DescriptionId")
                        .IsRequired();

                    b.HasOne("AspNetCoreContentLocalization.Data.Entities.LocalizationSet", "Name")
                        .WithOne()
                        .HasForeignKey("AspNetCoreContentLocalization.Data.Entities.Book", "NameId")
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetCoreContentLocalization.Data.Entities.Library", b =>
                {
                    b.HasOne("AspNetCoreContentLocalization.Data.Entities.LocalizationSet", "Name")
                        .WithMany()
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetCoreContentLocalization.Data.Entities.Localization", b =>
                {
                    b.HasOne("AspNetCoreContentLocalization.Data.Entities.Culture", "Culture")
                        .WithMany()
                        .HasForeignKey("CultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreContentLocalization.Data.Entities.LocalizationSet", "LocalizationSet")
                        .WithMany("Localizations")
                        .HasForeignKey("LocalizationSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
